services:
  db:
    image: postgis/postgis:16-3.4
    container_name: oburus-postgres
    environment:
      - POSTGRES_USER=oburus
      - POSTGRES_PASSWORD=oburus_pass
      - POSTGRES_DB=oburus
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ../infra/db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U oburus -d oburus"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 20s

  neo4j:
    image: neo4j:5.20
    container_name: oburus-neo4j
    environment:
      - NEO4J_AUTH=neo4j/oburus_pass
      - NEO4J_PLUGINS=["apoc", "graph-data-science"]
    ports:
      - "7474:7474"   # Neo4j Browser
      - "7687:7687"   # Bolt
    volumes:
      - neo4j_data:/data

  api:
    build: ../apps/api
    container_name: oburus-api
    environment:
      DB_HOST: db
      DB_PORT: "5432"
      DB_NAME: oburus
      DB_USER: oburus
      DB_PASS: oburus_pass
      RECO_URL: http://recommender:8000
      NODE_ENV: development
    depends_on:
      db:
        condition: service_healthy
      recommender:
        condition: service_started
    ports:
      - "3000:3000"
    volumes:
      - ../apps/api:/app

  recommender:
    build: ../apps/recommender
    container_name: oburus-recommender
    ports:
      - "8000:8000"
    volumes:
      - ../apps/recommender:/app
    environment:
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASS: oburus_pass

volumes:
  pg_data:
  neo4j_data:
